# Provide the reference frame, joint axes, their location, and the location of the tool
# The following info is for the Kinova Gen3 7DoF robot arm
ref_frame:
  - name: base_link

joints:
  - name: joint_1
    w: [0, 0, -1]
    q: [0, 0, 0.15643]

  - name: joint_2
    w: [0, 1, 0]
    q: [0, -0.00537, 0.28481]

  - name: arm0_elbow_pitch
    w: [0, 1, 0]
    q: [0.3385, -0.0001, -0.0003]

  - name: arm0_elbow_roll
    w: [1, 0, 0]
    q: [0.7428, -0.0003, 0.0693]

  - name: arm0_wrist_pitch
    w: [0, 1, 0]
    q: [0.7428, -0.0003, 0.0693]

  - name: arm0_wrist_roll
    w: [1, 0, 0]
    q: [0.7428, -0.0003, 0.0693]

tool:
  - name: arm0_tool0
    q: [0.9383, 0.0005, 0.0664]
