# Provide the reference frame, joint axes, their location, and the location of the tool
# The following info is for the Kinova Gen3 7DoF robot arm
ref_frame:
  - name: base_link

robot_joints:
  - name: joint_1
    w: [0, 0, -1]
    q: [0, 0, 0.15643]

  - name: joint_2
    w: [0, 1, 0]
    q: [0, -0.00537, 0.28481]

  - name: joint_3
    w: [0, 0, -1]
    q: [0, -0.0118, 0.4952]

  - name: joint_4
    w: [0, 1, 0]
    q: [0, -0.0182, 0.7056]

  - name: joint_5
    w: [0, 0, -1]
    q: [0, -0.0246, 0.9140]

  - name: joint_6
    w: [0, 1, 0]
    q: [0, -0.0246, 1.0199]

  - name: joint_7
    w: [0, 0, -1]
    q: [0, -0.0246, 1.1258]

gripper_joint:
  - name: robotiq_85_left_knuckle_joint

tool:
  - name: manual_grasp_link # Tool frame name, example: arm0_tool0. This is usually at the center of the palm
    q: [0, -0.0246, 1.381] # Tool frame location, example: [0.9383, 0.0005, 0.0664]
