# *** ROS-related attributes pertaining to kinova_gen3_7dof for visualization of joint trajectories*** #

/**: # to enable parameter usage across different nodes
  ros__parameters:

    joint_states_topic: "/joint_states" # Joint states topic name

    planning_group: "manipulator" # MoveIt planning group name

    ref_frame: "base_link" # Default frame where the CCA planning plugin will show the screw interactive marker
    tool_frame: "manual_grasp_link " # Frame that follows the screw path for planning purposes

    rviz_fixed_frame: "base_link" # Base frame from the urdf
