# *** ROS-related attributes pertaining to kinova_gen3_7dof for visualization of joint trajectories*** #

/**: # to enable parameter usage across different nodes
  ros__parameters:

    joint_states_topic: "/joint_states" # Joint states topic name

    planning_group: "manipulator" # MoveIt planning group name

    ref_frame: "base_link" # Default frame where the CCA planning plugin will show the screw interactive marker

    ee_frame: "end_effector_link" # End-effector frame

    tool_frame: "cca_tool_frame" # End-effector frame

    ee_to_tool_offset: [0.0, 0.0, 0.112] # Location of the tool in the EE frame

    rviz_fixed_frame: "base_link" # Base frame from the urdf
