"""ROS 2 launch script for CCA robot trajectory validation and optional visualization with RViz.

Author: Crasun Jans

This launch script visualizes and validates joint trajectories generated by the
Closed-Chain Affordance (CCA) planner. It launches:
- robot_state_publisher: Publishes robot transforms from URDF
- cca_ros_viz_node: Validates and visualizes CCA trajectories
- rviz2: Interactive 3D visualization (optional)

The robot-specific configuration is automatically imported from cca_<robot>_settings.py in the
same directory.

### Usage:
    ros2 launch cca_kinova_gen3_7dof cca_kinova_gen3_7dof_ros_viz.launch.py
    ros2 launch cca_kinova_gen3_7dof cca_kinova_gen3_7dof_ros_viz.launch.py launch_rviz:=true
====================================================================
THIS FILE IS AUTOGENERATED AND USUALLY DOES NOT REQUIRE MODIFICATION.
====================================================================
"""

from launch import LaunchDescription
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

import os, importlib.util
from launch_ros.substitutions import FindPackageShare

def load_settings_module(package='cca_kinova_gen3_7dof', module_name='cca_kinova_gen3_7dof_settings'):
    """Dynamically load the CCA settings module from a package's launch folder."""
    try:
        settings_path = os.path.join(
            FindPackageShare(package).find(package), 'launch', f'{module_name}.py'
        )
        spec = importlib.util.spec_from_file_location(module_name, settings_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    except Exception as e:
        print(f"[ERROR] Failed to load settings module '{module_name}' from package '{package}': {e}")
        raise RuntimeError(f"Unable to import {module_name} from {package}/launch") from e

# Load module and expose its functions
cca_robot_settings = load_settings_module()
declare_launch_args = cca_robot_settings.declare_launch_args
define_robot_paths_and_settings = cca_robot_settings.define_robot_paths_and_settings
generate_robot_description_content = cca_robot_settings.generate_robot_description_content
generate_robot_description_semantic_content = cca_robot_settings.generate_robot_description_semantic_content


def generate_launch_description():
    """Generate the complete launch description for robot visualization.

    Returns:
        LaunchDescription: Complete launch configuration
    """
    # Get robot-specific configuration
    args = declare_launch_args()
    robot_args = args["robot_args"]
    base_args = args["base_args"]
    settings = define_robot_paths_and_settings()

    # Generate robot descriptions
    robot_description = generate_robot_description_content(
        package_name=settings["urdf_package"],
        urdf_rel_path=settings["urdf_xacro_path"],
        launch_args=robot_args,
    )

    robot_description_semantic = generate_robot_description_semantic_content(
        package_name=settings["srdf_package"],
        srdf_path=settings["srdf_path"],
        all_launch_args=robot_args,
        srdf_arg_usage=settings["srdf_arg_usage"],
        srdf_subset_args=settings.get("srdf_subset_args"),
    )

    # Get CCA validation and visualization setup parameters
    cca_viz_params = settings["cca_robot_ros_viz_setup_path"]

    # RViz configuration
    rviz_config = PathJoinSubstitution(
        [FindPackageShare("cca_ros_viz"), "rviz", "cca_ros_viz.rviz"]
    )

    # Prepare parameters
    use_sim_time = {"use_sim_time": LaunchConfiguration("use_sim_time")}
    params_common = [
        {"robot_description": robot_description},
        {"robot_description_semantic": robot_description_semantic},
        cca_viz_params,
        use_sim_time,
    ]

    # Define nodes
    return LaunchDescription(
        robot_args
        + base_args
        + [
            Node(
                package="robot_state_publisher",
                executable="robot_state_publisher",
                name="robot_state_publisher",
                output="screen",
                parameters=params_common,
            ),
            Node(
                package="cca_ros_viz",
                executable="cca_ros_viz_node",
                name="cca_ros_viz",
                output="screen",
                parameters=params_common,
            ),
            Node(
                package="rviz2",
                executable="rviz2",
                name="rviz2",
                output="screen",
                condition=IfCondition(LaunchConfiguration("launch_rviz")),
                arguments=["-d", rviz_config],
                parameters=params_common,
            ),
        ]
    )
