"""ROS 2 launch script to launch the CCA planner as an action server.

Author: Crasun Jans

This script launches the CCA planner as a ROS action server by loading `cca_ros_action_node` with
robot-specific CCA settings and robot description. You may also load the node under gdb for debugging
by using the debug arg.

The robot-specific configuration is automatically imported from cca_<robot>_settings.py in the
same directory.

### Usage:
    ros2 launch cca_kinova_gen3_7dof cca_kinova_gen3_7dof_action_server.launch.py
    ros2 launch cca_kinova_gen3_7dof cca_kinova_gen3_7dof_action_server.launch.py debug:=true
====================================================================
THIS FILE IS AUTOGENERATED AND USUALLY DOES NOT REQUIRE MODIFICATION.
====================================================================
"""

import os, importlib.util
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

def load_settings_module(package='cca_kinova_gen3_7dof', module_name='cca_kinova_gen3_7dof_settings'):
    """Dynamically load the CCA settings module from a package's launch folder."""
    try:
        settings_path = os.path.join(
            FindPackageShare(package).find(package), 'launch', f'{module_name}.py'
        )
        spec = importlib.util.spec_from_file_location(module_name, settings_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        print(f"[INFO] Loaded settings module: {settings_path}")
        return module
    except Exception as e:
        print(f"[ERROR] Failed to load settings module '{module_name}' from package '{package}': {e}")
        raise RuntimeError(f"Unable to import {module_name} from {package}/launch") from e


# Load module and expose key functions
cca_robot_settings = load_settings_module()
declare_launch_args = cca_robot_settings.declare_launch_args
define_robot_paths_and_settings = cca_robot_settings.define_robot_paths_and_settings
generate_robot_description_content = cca_robot_settings.generate_robot_description_content

def generate_launch_description():
    """Generate the complete launch description for the CCA action server.

    Returns:
        LaunchDescription: Complete launch configuration
    """

    # Get robot-specific configuration
    args = declare_launch_args()
    robot_args = args["robot_args"]
    base_args = args["base_args"]
    settings = define_robot_paths_and_settings()

    # Generate robot description
    robot_description = generate_robot_description_content(
        package_name=settings["urdf_package"],
        urdf_rel_path=settings["urdf_xacro_path"],
        launch_args=robot_args,
    )

    # Get CCA ROS setup parameters for the robot
    cca_robot_setup_params = settings["cca_robot_ros_setup_path"]

    # Declare debug mode argument
    debug_arg = DeclareLaunchArgument(
        'debug',
        default_value='false',
        description="Enable GDB debug mode for the CCA planner node.",
    )

    debug = LaunchConfiguration("debug")
    node_prefix = PythonExpression([
        "'xterm -e gdb -ex run --args' if '", debug, "' == 'true' else ''"
    ])
    emulate_tty = PythonExpression(["'", debug, "' == 'true'"])

    # Node parameters
    params = [
        {"robot_description": robot_description},
        cca_robot_setup_params,
    ]

    return LaunchDescription(
        robot_args
        + base_args
        + [debug_arg]
        + [
            Node(
                package="cca_ros_action",
                executable="cca_ros_action_node",
                name="cc_affordance_planner_ros",
                output="screen",
                prefix=[node_prefix],
                emulate_tty=emulate_tty,
                parameters=params,
            ),
        ]
    )
